### ISSUE TITLE
Check re-usability 

### ISSUE THREAD

**Issue by fehrhart** [egonw/egonw.github.com#14]
Please check re-usability of the genetic variation and phenotype data

List of databases can be found here (please add comments in column J):
 https://docs.google.com/spreadsheets/d/17Vb3NDzlvdGP0FMCXuZhkjgA4sdDlNSOxVpttTh0W5A/edit#gid=0

**Comment by egonw** [comment]
Not quite the tracker I had in mind :) But no worries; works for me :)
