### ISSUE TITLE
Citation.js is broken on your page

### ISSUE THREAD

**Issue by larsgw** [egonw/egonw.github.com#9]
[Citation.js](https://github.com/larsgw/citation.js) is broken on your page because the files you link to have moved. I'll make pull request to accommodate the changes, but consider hosting the files yourself.

**Comment by larsgw** [comment]
Well, it happened again.

**Comment by egonw** [comment]
OK :)

**Comment by larsgw** [comment]
I made a pull request, apparently it doesn't show up in closed issues. Anyway, the file should stay in the same place for a while for now.
